# action.yml
name: 'Current PHP Releases'
description: 'Get data from PHPReleases.com'
outputs:
  minimum: #id of output
    description: 'The minimum active support PHP release'
  latest: #id of output
    description: 'The latest PHP release'
  range:
    description: 'Should be a range'
runs:
  using: 'docker'
  image: 'Dockerfile'
