# action.yml
name: 'Current PHP Releases'
description: 'Get data from PHPReleases.com'
outputs:
  releases: #id of output
    description: 'The data returned from phpreleases.com'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}