on: [push]

jobs:
  current_php_releases:
    runs-on: ubuntu-latest
    name: Fetch all current PHP Releases
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get the PHPReleases output
        uses: ./ # Uses an action in the root directory
        run: echo "PHP releases returned ${{ steps.hello.outputs.releases }}"