on: [push]

jobs:
  current_php_releases:
    runs-on: ubuntu-latest
    name: Fetch all current PHP Releases
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch Current Releases
        uses: ./
        id: releases
      - name: Get the PHPReleases output
        run: echo "PHP releases returned ${{ steps.releases.outputs.releases }}"
