on: [push]

jobs:
  output_releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch Current Releases
        uses: ./
        id: releases
        
  current_php_releases:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ["${{ steps.releases.outputs.minimum }}", "${{ steps.releases.outputs.latest }}"]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Echo PHP
        run: echo ${{ matrix.php }}
